'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Forza_Horizon_3_Steam_Edition.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_05_ENGINEROOM_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_05_ENGINEROOM_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_06_COMMUNICATION_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_06_COMMUNICATION_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_12_HYDROTHUNDER_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_12_HYDROTHUNDER_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Pinger1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Pinger1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Steam7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Steam7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices12() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices13() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property AMB_EC_Voices9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("AMB_EC_Voices9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property camera1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("camera1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coconu3t() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coconu3t", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coconut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coconut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coconut1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coconut1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coconut2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coconut2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_static_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_static_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_static_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_static_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_static_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_static_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_static_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_static_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property comm_voice_9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("comm_voice_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Control_Room_Loop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Control_Room_Loop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Control_Room_Loop_ver2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Control_Room_Loop_ver2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dfdfdfdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfdfdfdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Forzaa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forzaa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Forzaas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forzaas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Info_Screen_In() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Info_Screen_In", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Info_Screen_In_MSurr() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Info_Screen_In_MSurr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Info_Screen_Out() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Info_Screen_Out", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Info_Screen_Out_MSurr() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Info_Screen_Out_MSurr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Main_Menu_In_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Main_Menu_In_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Main_Menu_Out_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Main_Menu_Out_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Sub_Menu_In_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Sub_Menu_In_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Games_Sub_Menu_Out_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Games_Sub_Menu_Out_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_A_Button_Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_A_Button_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_B_Button_Back() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_B_Button_Back", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Completion_Beep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Completion_Beep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Delete_Destroy() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Delete_Destroy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Error_Message_B() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Error_Message_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Keyboard_Stroke_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Keyboard_Stroke_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Keyboard_Stroke_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Keyboard_Stroke_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Main_MenuBack3ver2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Main_MenuBack3ver2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Main_MenuFwd3ver2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Main_MenuFwd3ver2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Progress_Bar() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Progress_Bar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Global_Scroll_Beep() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Global_Scroll_Beep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grabbber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grabbber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Memory_Controller_Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Memory_Controller_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Memory_Games_Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Memory_Games_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Memory_Memory_Slot_Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Memory_Memory_Slot_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Music_CD_Select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Music_CD_Select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Music_Main_Menu_In_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Music_Main_Menu_In_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Music_Main_Menu_Out_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Music_Main_Menu_Out_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Music_Select_Track_In_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Music_Select_Track_In_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Music_Select_Track_Out_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Music_Select_Track_Out_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEANUT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEANUT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEANUTBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEANUTBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEANUTEEEE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEANUTEEEE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sendbtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sendbtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Settings_Lang_SubMenu_Sel() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Settings_Lang_SubMenu_Sel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Settings_Main_Menu_In_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Settings_Main_Menu_In_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Settings_Main_Menu_Out_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Settings_Main_Menu_Out_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Settings_Parent_SubMenu_Sel() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Settings_Parent_SubMenu_Sel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Settings_Sub_Menu_In_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Settings_Sub_Menu_In_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Settings_Sub_Menu_Out_LR() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Settings_Sub_Menu_Out_LR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property txting_press_a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("txting_press_a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property warning() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("warning", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
